DEBUG=1
SECRET_KEY=foo
DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
SQL_ENGINE=django.db.backends.postgresql
SQL_DATABASE=django_dev
SQL_USER=django
SQL_PASSWORD=django
SQL_HOST=db_psql
SQL_PORT=5432
DATABASE=postgres
EMAIL_HOST_USER=projekt.io.email@gmail.com
EMAIL_HOST_PASSWORD=ProjektIO2020
POSTGRES_USER=django
POSTGRES_PASSWORD=django
POSTGRES_DB=django_dev
GOOGLE_API_ID=669089852363-f6hpqanqdqu6fl81jv328ashpaa0kh4f.apps.googleusercontent.com
GOOGLE_API_SECRET=EKun1uCRORbvgICQadLyKXUf
GOOGLE_API_PROJECT_ID=pro-contact-296410