# Generated by Django 3.0.7 on 2020-09-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'none')], default='none', max_length=10, verbose_name="User's gender"),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='<b>Address in format</b>: [STREET NAME] [NUMBER], [CITY]', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, help_text='<b>Birthday date in format:</b> YYYY-MM-DD', verbose_name='Date of birth'),
        ),
    ]
