# Generated by Django 3.0.7 on 2020-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200920_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=9, verbose_name='Phone number'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
