# Generated by Django 3.0.7 on 2020-10-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201017_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, help_text='<b>Birthday date in format:</b> YYYY-MM-DD', null=True, verbose_name='Date of birth'),
        ),
    ]
