# Generated by Django 3.0.7 on 2020-11-01 22:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='defaults/default-user.png', upload_to=users.models.get_file_path),
        ),
    ]
