# Generated by Django 3.0.7 on 2020-10-24 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Grade's name")),
                ('start_year', models.DateField(verbose_name='Grade start year')),
                ('max_number_of_students', models.IntegerField(default=120, help_text='Maximum number of student at Grade')),
                ('profile', models.CharField(choices=[('CS', 'Computer Science')], max_length=20)),
                ('students', models.ManyToManyField(related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_grades', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ('name', 'start_year'),
                'unique_together': {('name', 'start_year')},
            },
        ),
    ]
