# Generated by Django 3.0.7 on 2020-11-27 21:40

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Course's name")),
                ('description', models.TextField(blank=True, null=True)),
                ('ects', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('code_meu', models.CharField(max_length=30, verbose_name='MEU Code')),
                ('has_exam', models.BooleanField(default=False)),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('language', models.CharField(choices=[('EN', 'English'), ('PL', 'Polish')], max_length=20)),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='WWW site')),
                ('lecture_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('labs_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=courses.models.get_file_path, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.AlterField(
            model_name='grade',
            name='profile',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IS', 'Intelligent Systems')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='students',
            field=models.ManyToManyField(related_name='grades', to='users.Student', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_grades', to='users.Student', verbose_name='Supervisor'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Lecture's title")),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=5400))),
                ('reminders', models.BooleanField(default=True)),
                ('time_delta', models.DurationField(blank=True, default=datetime.timedelta(days=7), null=True)),
                ('event_id', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('hangout_link', models.CharField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.Course')),
                ('files', models.ManyToManyField(blank=True, to='courses.CourseFile')),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Lecture's title")),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=5400))),
                ('reminders', models.BooleanField(default=True)),
                ('time_delta', models.DurationField(blank=True, default=datetime.timedelta(days=7), null=True)),
                ('event_id', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('hangout_link', models.CharField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='courses.Course')),
                ('files', models.ManyToManyField(blank=True, to='courses.CourseFile')),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="Course group's name")),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course')),
                ('files', models.ManyToManyField(blank=True, to='courses.CourseFile')),
                ('students', models.ManyToManyField(related_name='students_groups', to='users.Student', verbose_name='Students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_teaching', to='users.Teacher')),
            ],
            options={
                'verbose_name': 'Course Group',
                'verbose_name_plural': 'Course Groups',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='files',
            field=models.ManyToManyField(blank=True, to='courses.CourseFile'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Grade'),
        ),
        migrations.AddField(
            model_name='course',
            name='head_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_running', to='users.Teacher', verbose_name='Head teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses_teaching', to='users.Teacher', verbose_name='Teachers'),
        ),
    ]
