# Generated by Django 3.0.7 on 2020-10-24 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Course's name")),
                ('description', models.TextField()),
                ('code_meu', models.CharField(max_length=30, verbose_name='MEU Code')),
                ('has_exam', models.BooleanField(default=False)),
                ('semester', models.IntegerField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('PL', 'Polish')], max_length=20)),
                ('site', models.CharField(max_length=255, verbose_name='WWW site')),
                ('lecture_hours', models.IntegerField()),
                ('labs_hours', models.IntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Grade')),
                ('head_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_running', to=settings.AUTH_USER_MODEL, verbose_name='Head teacher')),
                ('teachers', models.ManyToManyField(related_name='courses_teaching', to=settings.AUTH_USER_MODEL, verbose_name='Teachers')),
            ],
        ),
    ]
