# Generated by Django 3.0.7 on 2020-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201127_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
