# Generated by Django 3.0.7 on 2020-10-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
    ]
