# Generated by Django 3.0.7 on 2020-11-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0003_auto_20201128_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_students',
            field=models.ManyToManyField(related_name='additional_courses', to='users.Student'),
        ),
    ]
