# Generated by Django 3.0.7 on 2020-10-29 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201029_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='labs_hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecture_hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WWW site'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='profile',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IS', 'Intelligent Systems')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('name', 'start_year')},
        ),
    ]
