# Generated by Django 3.0.7 on 2020-10-30 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_teacher'),
        ('courses', '0004_auto_20201029_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='head_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_running', to='users.Teacher', verbose_name='Head teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses_teaching', to='users.Teacher', verbose_name='Teachers'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='students',
            field=models.ManyToManyField(related_name='grades', to='users.Student', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_grades', to='users.Student', verbose_name='Supervisor'),
        ),
    ]
