# Generated by Django 3.0.7 on 2020-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201128_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratories',
            name='course',
        ),
        migrations.RemoveField(
            model_name='laboratories',
            name='files',
        ),
        migrations.DeleteModel(
            name='CourseGroup',
        ),
        migrations.DeleteModel(
            name='Laboratories',
        ),
    ]
