# Generated by Django 3.0.7 on 2020-10-30 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_teacher'),
        ('courses', '0005_auto_20201030_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_grades', to='users.Student', verbose_name='Supervisor'),
        ),
    ]
