# Generated by Django 3.0.7 on 2020-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201128_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='create_event',
            field=models.BooleanField(default=False),
        ),
    ]
