# Generated by Django 3.0.7 on 2020-10-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
