# Generated by Django 3.0.7 on 2020-12-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201205_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturemark',
            name='mark',
            field=models.DecimalField(choices=[(2.0, 2.0), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=10, max_digits=11),
        ),
    ]
