# Generated by Django 3.0.7 on 2020-10-31 17:05

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201031_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=courses.models.get_file_path, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='files',
            field=models.ManyToManyField(to='courses.CourseFile'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='files',
            field=models.ManyToManyField(to='courses.CourseFile'),
        ),
    ]
