# Generated by Django 3.0.7 on 2020-12-06 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201205_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturemark',
            name='mark',
            field=models.DecimalField(decimal_places=10, max_digits=13, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
