# Generated by Django 3.0.7 on 2020-10-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201031_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='files',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='files',
        ),
        migrations.DeleteModel(
            name='CourseFile',
        ),
    ]
