# Generated by Django 3.0.7 on 2020-12-06 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0010_auto_20201206_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Lecture's title")),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=5400))),
                ('reminders', models.BooleanField(default=True)),
                ('time_delta', models.DurationField(blank=True, default=datetime.timedelta(days=7), null=True)),
                ('show', models.BooleanField(default=False)),
                ('create_event', models.BooleanField(default=False)),
                ('event_id', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('hangout_link', models.CharField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='courses.Course')),
                ('files', models.ManyToManyField(blank=True, to='courses.CourseFile')),
                ('students', models.ManyToManyField(related_name='laboratories', to='users.Student')),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
    ]
