# Generated by Django 3.0.7 on 2020-12-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0011_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='students',
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.Course')),
                ('students', models.ManyToManyField(related_name='laboratories', to='users.Student')),
            ],
        ),
        migrations.AddField(
            model_name='laboratory',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory', to='courses.CourseGroup'),
        ),
    ]
