# Generated by Django 3.0.7 on 2020-10-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='files',
            field=models.ManyToManyField(blank=True, to='courses.CourseFile'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='files',
            field=models.ManyToManyField(blank=True, to='courses.CourseFile'),
        ),
    ]
