# Generated by Django 3.0.7 on 2020-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20201206_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
