# Generated by Django 3.0.7 on 2020-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0013_coursegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='laboratories', to='users.Student'),
        ),
    ]
