# Generated by Django 3.0.7 on 2020-11-08 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ects',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
