# Generated by Django 3.0.7 on 2020-11-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_ects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLectureSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="Course lecture's name")),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
