# Generated by Django 3.0.7 on 2020-12-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20201206_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
    ]
