# Generated by Django 3.0.7 on 2020-12-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0015_auto_20201210_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='courses.Course')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='users.Teacher')),
            ],
            options={
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
