# Generated by Django 3.0.7 on 2020-12-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0016_coursenotice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursenotice',
            options={'ordering': ('-created_at', 'title')},
        ),
        migrations.AddField(
            model_name='coursenotice',
            name='not_viewed',
            field=models.ManyToManyField(blank=True, related_name='not_viewed_notices', to='users.Student'),
        ),
    ]
