# Generated by Django 3.0.7 on 2020-12-19 14:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0017_auto_20201213_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=10, max_digits=13, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.Laboratory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_marks', to='users.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setted_laboratory_marks', to='users.Teacher')),
            ],
            options={
                'ordering': ('date', 'laboratory'),
            },
        ),
    ]
