# Generated by Django 3.0.7 on 2020-12-19 14:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0018_laboratorymark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=10, max_digits=13, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_marks', to='users.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setted_lecture_marks', to='users.Teacher')),
            ],
            options={
                'ordering': ('date', 'course'),
            },
        ),
        migrations.RemoveField(
            model_name='lecturemark',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='lecturemark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lecturemark',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='LaboratoryMark',
        ),
        migrations.DeleteModel(
            name='LectureMark',
        ),
    ]
