# Generated by Django 3.0.7 on 2020-12-19 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20201219_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemark',
            name='mark',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
