# Generated by Django 3.0.7 on 2020-12-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0020_auto_20201219_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_marks', to='users.Student'),
        ),
    ]
