# Generated by Django 3.0.7 on 2020-12-20 14:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0021_auto_20201219_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemark',
            options={'ordering': ('-date',)},
        ),
        migrations.CreateModel(
            name='FinalCourseMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_marks', to='courses.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_final_marks', to='users.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setted_final_marks', to='users.Teacher')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('student', 'course')},
            },
        ),
    ]
