# Generated by Django 3.0.7 on 2020-12-24 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20201220_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 24, 12, 15, 54, 500804, tzinfo=utc)),
        ),
    ]
