# Generated by Django 3.0.7 on 2020-12-27 14:20

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0023_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 27, 14, 20, 31, 24209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grade',
            name='profile',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IS', 'Intelligent Systems'), ('AC', 'Automatics Control'), ('MA', 'Maths')], max_length=20),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.Laboratory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setted_assignments', to='users.Teacher')),
            ],
        ),
    ]
