# Generated by Django 3.0.7 on 2021-01-09 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201103_1703'),
        ('courses', '0024_auto_20201227_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ('date',), 'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterField(
            model_name='course',
            name='additional_students',
            field=models.ManyToManyField(blank=True, null=True, related_name='additional_courses', to='users.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 10, 12, 41, 487878, tzinfo=utc)),
        ),
    ]
