# Generated by Django 3.0.7 on 2021-01-10 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20210109_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 10, 14, 1, 10, 19469, tzinfo=utc)),
        ),
    ]
